name: DCO report

on:
  workflow_run:
    workflows: ["DCO"]
    types:
      - completed

permissions:
  contents: none

jobs:
  comment:
    name: Organization
    uses: openslide/.github/.github/workflows/dco-report.yml@69fb55fcf0f08a1974db9a2089506f5afaf64404 # main at 2026-07-07
    secrets:
      OPENSLIDE_BOT_TOKEN: ${{ secrets.OPENSLIDE_BOT_TOKEN }}
